### ISSUE TITLE
thanks a lot

### ISSUE THREAD

**Issue by riteshkgupta395** [Nikasan/Java_Cucumber_RestAssured_Alure#2]
tes

**Comment by Nikasan** [comment]
Hi! Have you seen this videos?
1 part: https://www.youtube.com/watch?v=UhK6QwWdYX0&t=0s 
2 part: https://www.youtube.com/watch?v=5cWRP9KR-KQ
They are on Russian language, but anyway you cat find original repository with code.
My repository just for my study and it is not work perfect =)
